# Generated by Django 3.1.4 on 2020-12-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0002_cached_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='fields',
            name='q',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
